### ISSUE TITLE
adjusting the size

### ISSUE THREAD

**Issue by murad1981** [sketch204/ActivityIndicators#1]
There is no way to adjust the size of the indicator, it's fixed to 40 X 40, I wish the size to be exposed.

**Comment by sketch204** [comment]
@murad1981, Apologies for the late response. For some reason I did not get a notification about this new issue. This should now be resolved in 37e691b20217c3fd63e6fd87022e35d380b4f826. The main README should also have docs on how to resize indicators as of 19a690c159be5fa9e32731026ec183ad52438360. Check the bottom of the README.
